require 'faraday'
require 'id'
require 'active_support/core_ext/hash/conversions'
require 'doctors/address'
require 'doctors/coordinate'
require 'doctors/practice'
require 'doctors/search'
require 'doctors/search/xml_parser'
